### PR TITLE
upgrade connect to 3.4.1 and replace connect.router with connect-route

### PR DESCRIPTION
**Pull request by haoruiqian**
Upgrade to use latest connection version, replace connect.router with connect-route since connect.router has been removed.

### CODE REVIEW

**Comment by shao** [comment]
@michaelnsj @StanleyShen @samdai Please help review.

Thanks.

**Comment by michaelnsj** [comment]
looks good to me.

**Comment by shao** [comment]
Do we need to build this?

**Comment by haoruiqian** [comment]
No, when deploy oauth code to cf vm, it will run "npm install" to download these code to the vm automatically.

**Comment by shao** [comment]
OK.  Thanks for the confirmation.

**Pull request merged**
